### ISSUE TITLE
Be able to use the original object in cloned properties

### ISSUE THREAD

**Issue by ixarlie** [myclabs/DeepCopy#100]
Hi, in my example I need to have access to the "source" object because I'd like to link it in one of the cloned properties.

```php
class Foo
{
    /** @var Foo */
    protected $source;
}
// A DeepCopy\Filter\Filter would do this.
$cloner = new DeepCopy();
$foo    = new Foo();
$result = $cloner->copy($foo);

// $result->source == $foo;
```

The `DeepCopy\Filter\Filter::apply($object, $property, $objectCopier)` interface should allow the "source" object, therefore `DeepCopy::copyObjectProperty` aswell.

My first idea was to extend DeepCopy and override some methods, but is too private. I know this feature is not a "cloning" thing but it could be interesting. Is there other way to accomplish??

Thanks!

**Comment by theofidry** [comment]
wouldn't a regular clone do the work?

**Comment by ixarlie** [comment]
Maybe my example class was very simple but I was interested in doing it at any level using the recursivity. So not sure if a regular cloning could help me, but to be honest this feature mess the basic cloning functionality. So I should look for any solution. Thanks!
