### ISSUE TITLE
I've got redeclared function deep_copy

### ISSUE THREAD

**Issue by kotakorange** [myclabs/DeepCopy#102]
I've got this error while do phpunit.. PHP Fatal error:  Cannot redeclare DeepCopy\deep_copy() (previously declared in /usr/share/php/DeepCopy/deep_copy.php:13)
Maybe add check function_exists before declare function should be a solution.

**Comment by theofidry** [comment]
I would rather check why `deep_copy` is being required twice. It is registered to Composer so Composer takes care of the autoloading and this should work as it is.

**Comment by theofidry** [comment]
Closing this as I don't think there is anything to change here: if you include the same file twice it can break because the function is already declared but it is also true for constants and classes. I would rather fix the calling code than adding guard everywhere for this
