### ISSUE TITLE
Cloning bidirectional relations and keep the same data in cloned entities

### ISSUE THREAD

**Issue by paquitodev** [myclabs/DeepCopy#11]
I have one doubt lets said that I've entities A, B and C, A hasMany B and B hasMany C but C can have many B also, how should my code looks like? Also I want to clone A but keeping the same information in cloned B and C meaning the only I want to update is the reference to the cloned A, is that what DeepClone does? Any advice? Could you provide an answer explaining this?

**Comment by mnapoli** [comment]
Hey! This seems like a pretty complex use case, I will not do all the code for you but have a look at the documentation, you can ask for some properties to stay unchanged using the [KeepFilter](https://github.com/myclabs/DeepCopy#keepfilter).

I think the best way for you to get started it to write some tests in your app and then iterate slowly until you get it right. But yes, this package should definitely help you do what you want, it is meant to do exactly that and has a lot of options that should cover your needs.

If you have a specific question about a feature please feel free to ask here.
