### ISSUE TITLE
unexpected function error in deep copy

### ISSUE THREAD

**Issue by benmadin** [myclabs/DeepCopy#122]
Hello,

I just did a composer update, and my website went down. The logs showed this message:

`[Fri Jun 29 01:10:09.028655 2018] [:error] [pid 22125] [client 10.0.10.4:47366] PHP Parse error:  syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\\\ (T_NS_SEPARATOR) in /var/www/website/vendor/myclabs/deep-copy/src/DeepCopy/deep_copy.php on line 5
`

the composer.lock file shows

```            
"name": "myclabs/deep-copy",
"url": "https://github.com/myclabs/DeepCopy.git",
"url": "https://api.github.com/repos/myclabs/DeepCopy/zipball/3e01bdad3e18354c3dce54466b7fbe33a9f9f7f8",
"myclabs/deep-copy": "self.version"
"myclabs/deep-copy": "^1.3",
```

not sure even what this does, but commenting out line 5 in deep_copy.php restored my website to functioning.

cheers

Ben

**Comment by theofidry** [comment]
If I read this correctly the line you are talking about is:

```
use function function_exists;
```

Which is a simple use statement, but for a function not a class. On what version was your website running?

**Comment by mjvanmiddelaar** [comment]
I ran into the same issue from command line PHP Version 7.2.1  DeepCopy version "1.8.1"

`Parse error: parse error, expecting `"identifier (T_STRING)"' or `"\\ (T_NS_SEPARATOR)"' in .../vendor/myclabs/deep-copy/src/DeepCopy/deep_copy.php on line 5
`

**Comment by mjvanmiddelaar** [comment]
- Updating myclabs/deep-copy (1.8.1 => 1.8.0): Downloading (100%)  solves the problem.

**Comment by theofidry** [comment]
Sorry I can't reproduce it at all, could you give more informations?

- The PHP version (do double check that the one executing the file is the php binary you are thinking of)
- The OS
- The version 1.8.1 confirmed?

It sounds absurd but could you also paste the content of that file? I really can't imagine what is causing this issue...

**Comment by mjvanmiddelaar** [comment]
Ah! It seemed my #!/usr/bin/env php was using native mac osx php 5.5.38 which was different from my bash php version which uses MAMP's version instead. - ```use function``` is available from 5.6+.

Issue solved. Thanks for the double check hint, (i used var_dump(phpversion()); die(); in my code to make sure)

**Comment by theofidry** [comment]
I guess it's the same for the original issue then :)

**Comment by walteratapukan** [comment]
> * Updating myclabs/deep-copy (1.8.1 => 1.8.0): Downloading (100%)  solves the problem.

hi Sir... how to update the myclabs/deep-copy ?

i got the same problem when upload to server. i use php 7 in my pc, and 5.> in the server.

**Comment by igpf** [comment]
> * deep-copy

thank you, same here.

**Comment by theofidry** [comment]
Sorry guys, but there is absolutely nothing special in DeepCopy. Any `Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\\\ (T_NS_SEPARATOR)` is indicator you are not using the right PHP version and deep-copy has no control over how composer download it so there is nothing to do here

**Comment by taufardh** [comment]
This error ruined my project... dunno what happen... in local that's fine.. but when uploaded to server that's error

**Comment by theofidry** [comment]
@taufardh see my previous reply.

**Comment by taufardh** [comment]
ah thanks for replying.. I finally solve the problem,
1. make sure you know exact PHP version where your project run,
2. delete folder vendor and composer.lock
3. add this config to composer.json 
`{
    "config": {
        "platform": {
            "php": "5.5.35"  /*your PHP version*/
        }
    },
}`
4. composer install and voila!

I hope this can help others...

src: https://discourse.slimframework.com/t/syntax-error-in-deep-copy-php/2655
