### ISSUE TITLE
error on version 1.8.1: unexpected 'function' deep_copy.php on line 5

### ISSUE THREAD

**Issue by georgezim85** [myclabs/DeepCopy#125]
Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in /home/literatu/DockerProjects/docker-literatus-yii2/app/vendor/myclabs/deep-copy/src/DeepCopy/deep_copy.php on line 5

**Comment by georgezim85** [comment]
Error is being shown on CentOS 7, running with CPanel's EasyApache4 ea-php7.1 and ea-php7.2

**Comment by georgezim85** [comment]
Solved after add this to public_html/.htaccess
`<IfModule mime_module>
 AddType application/x-httpd-ea-php71 .php .php7 .phtml
</IfModule>`

**Comment by r-martins** [comment]
It may be related to php version as well. PHP 5.4 doesn't work with that.

**Comment by hipogea** [comment]
I solved this. To reset all .htaccess files into the server.

**Comment by theofidry** [comment]
As declared [here](https://github.com/myclabs/DeepCopy/blob/1.x/composer.json#L24) it is a PHP 7.1 package so yes it will not work with PHP 5.x. Not sure what the .htaccess files have to do with it
