### ISSUE TITLE
here is a problem on Php 7.2

### ISSUE THREAD

**Issue by nurbeknurjanov** [myclabs/DeepCopy#128]
PHP Parse error: syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T NS_SEPARATOR) in /vendor/myclabs/deep-copy/src/DeepCopy/deep_copy.php on line 5

**Comment by theofidry** [comment]
This is coming from `use function DeepCopy\deep_copy` which is a PHP7 feature, so please double check that you are effectively in PHP7.2 and not 5.x: don't forget while checking that the CLI might be using a different version than your web-server.

**Comment by nurbeknurjanov** [comment]
Thank you for your help. Yes, I run it from console. when I checked php version, I do this
`$ /opt/plesk/php/7.2/bin/php -v`
it shows
```
PHP 7.2.12 (cli) (built: Nov  9 2018 13:30:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube2
```

I will check it again. Will try to remove all other php versions.

**Comment by moggiex** [comment]
Howdy,

Here is the output from the console:

```
[centos@ip-172-0-0-0 httpdocs]$ /opt/plesk/php/7.2/bin/php -v
PHP 7.2.12 (cli) (built: Nov  9 2018 13:30:46) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.2.1, Copyright (c) 2002-2018, by ionCube Ltd.
    with Zend OPcache v7.2.12, Copyright (c) 1999-2018, by Zend Technologies
[centos@ip-172-0-0-0 httpdocs]$ sudo /opt/plesk/php/7.2/bin/php yii minify/all
PHP Parse error:  syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in /var/www/vhosts/bangtracker.com/httpdocs/vendor/myclabs/deep-copy/src/DeepCopy/deep_copy.php on line 7
[centos@ip-172-0-0-0 httpdocs]$
```
Matt

**Comment by theofidry** [comment]
I mean, see for yourself, there is really nothing special [here](https://github.com/myclabs/DeepCopy/blob/1.x/src/DeepCopy/deep_copy.php#L5):

```php
<?php

namespace DeepCopy;

use function function_exists;

if (false === function_exists('DeepCopy\deep_copy')) {}
```

And if it's not enough for you, you can check https://3v4l.org/faCPY

So clearly it's something else and not DeepCopy. I do not know what `yii minify/all` does, but I would look there instead.

**Comment by moggiex** [comment]
Howdy @theofidry, we finally got to the bottom of this last night, which was a permissions related issue.

You can close the Issue ans thanks for the help 👍 

Matt

**Comment by theofidry** [comment]
Glad you got it sorted

**Comment by amodisc** [comment]
> Howdy @theofidry, we finally got to the bottom of this last night, which was a permissions related issue.
> 
> You can close the Issue ans thanks for the help 👍
> 
> Matt

Hi Matt, how did you solve it exactly? what permissions were wrong and where?

Please let me know as I have the same problem
