### ISSUE TITLE
expecting `"identifier (T_STRING)"' or `"\\ (T_NS_SEPARATOR)"'

### ISSUE THREAD

**Issue by SophiaX-Solar** [myclabs/DeepCopy#134]
I use composer to install my yii2(version 2.0.17.) website.My PHP is 7.1.22
It can run when I use "php yii serve"
but when I config it in Nginx , there is error like this

"[error] 10742#0: *49 FastCGI sent in stderr: "PHP message: PHP Parse error:  parse error, expecting `"identifier (T_STRING)"' or `"\\ (T_NS_SEPARATOR)"' in /Users/Fei/yii/vendor/myclabs/deep-copy/src/DeepCopy/deep_copy.php on line 5" while reading response header from upstream, client: 127.0.0.1, server:"

**Comment by SophiaX-Solar** [comment]
I use the  file "deep_copy.php" from  branch2.x ec3f73a .It works

**Comment by theofidry** [comment]
Hi, this is probably due to your FastCGI using a different PHP binary than the one you use in the CLI and this one is most likely not PHP 7+.

**Comment by SophiaX-Solar** [comment]
yes , I look for php-fpm in the server ,It's PHP 5+.
Thank you for help
