### ISSUE TITLE
v1.8 and v1.9 broke PHPUnit v6 and v7 :-(

### ISSUE THREAD

**Issue by hopeseekr** [myclabs/DeepCopy#135]
## The Problem
My problem is that I'm creating a polyfill for Laravel's `env()` and I wish to target PHP 7.0 and above, because, you know, legacy. 

[**PHPUnit's Supported Versions page**](https://phpunit.de/supported-versions.html) clearly list PHPUnit 6.x as being compatible with PHP v7.0, yet one of its core dependencies, `myclab/deep-copy` apparently required 7.1 without a major version bump (shame on them!).

![image](https://user-images.githubusercontent.com/1125541/57432845-8fd04880-71fc-11e9-973a-b56974c65e17.png)

>    - Installation request for myclabs/deep-copy 1.9.1 -> satisfiable by myclabs/deep-copy[1.9.1].
>    - myclabs/deep-copy 1.9.1 requires php ^7.1 -> your PHP version (7.0.25) does not satisfy that requirement.

Thus to resolve, I had to `composer require --dev myclabs/deep-copy:'1.7.*' for PHP v7.0 and `1.8.*` for PHP v7.1.

## The Solution
Requiring a huge new version of PHP is obviously a major break of Semantic Versioning. 

You should simply change PHP support to `7.*` for the version 1.9 branch and release a new composer package.

**Comment by theofidry** [comment]
>Requiring a huge new version of PHP is obviously a major break of Semantic Versioning.

It is not: whilst it can't go in a patch release it can go in a minor version release.

>PHPUnit 6.x as being compatible with PHP v7.0, yet one of its core dependencies, myclab/deep-copy apparently required 7.1

Can you check that you are resolving this from the right PHP version? Since PHPUnit must depend on something like `myclab/deep-copy ^1.0`, versions prior to 1.8 should satisfy the condition.

**Comment by hopeseekr** [comment]
It's my bad. I resolved the issue by simply removing the `composer.lock` from the package. Then PHP 7.0 installs it correctly.

Thank you for your fast response and for pointing me in the right direction, indirectly.
