### ISSUE TITLE
Ever increasing memory usage

### ISSUE THREAD

**Issue by ProFire** [myclabs/DeepCopy#140]
I noticed that the memory usage is ever increasing for each clone, despite that I'm overwriting each clone. Here's how I test:

```
use DeepCopy\DeepCopy;
$originalDeepObj = new \SuperDeepObj();
for ($i = 0; $i < 50; $i++) {
    $clonedObj = (new DeepCopy())->copy($originalDeepObj);
    print_r(memory_get_peak_usage());
}
```
In each output, the value increases. Could my issue be related to DeepCopy or some quirks of PHP?

P.S. The SuperDeepObj in my original app has 5 levels of nested classes. I use PHP 7.3.10

**Comment by theofidry** [comment]
Isn't that expected? You are creating a new `DeepCopy` instance as well as an object clone at each iteration

**Comment by ProFire** [comment]
I think you're right. I've refactored the code not to create a new DeepCopy instance for each iteration and the memory allocation error isn't triggered. I guess this is not a DeepCopy issue. My bad.
