### ISSUE TITLE
Remove dependency on doctrine/common

### ISSUE THREAD

**Issue by bmack** [myclabs/DeepCopy#142]
Hey,

as far as I see, the need for doctrine/collections is necessary, but since this package was spread out of doctrine/common, we could drop the dependency on doctrine/common, as this package only needs doctrine/persistence and doctrine/collections, right?

Right now, when requiring deepcopy, doctrine/common is installed, but not needed.

What do you think?

**Comment by theofidry** [comment]
The doctrine packages are only required for dev to be able to test the Doctrine bridges. So they should not installed if you require deep-copy

**Comment by bmack** [comment]
Thanks for the quick reply. yeah, you are so right! Stupid me :(
