### ISSUE TITLE
PHP 7.4: Cloning of "uninitialized" typed properties not currently possible

### ISSUE THREAD

**Issue by BusterNeece** [myclabs/DeepCopy#143]
Hello!

I've been eager to update everything to PHP 7.4, which was just released last Thursday, but in the process I'm discovering edge cases where the new features of the language are causing issues with certain libraries.

One such issue is with typed properties: DeepCopy currently attempts to pull the value from the existing property, but there's a new "uninitialized" property state that, if you attempt to pull the value while it's in that state, throws a `TypeError` and won't proceed.

It was previously a useless check, but now `isset($obj->property)` will return false for uninitialized variables, which could be the only thing needed to bring the library into compliance with the new changes. If you're using Reflection stuff, there re also new Reflection-specific methods available.

I'm happy to PR in a fix if that would be helpful. Just let me know. :)

**Comment by mnapoli** [comment]
Hi @SlvrEagle23, a PR would be welcome indeed!
