### ISSUE TITLE
Running PHPUnit 8.5.1 got deprecation

### ISSUE THREAD

**Issue by arturslogins** [myclabs/DeepCopy#148]
Hello 

Running PHPUnit 8.5.1. and Symfony 4.4.  i got deprecation warning on running php unit tests. 

Other deprecation notices (1)
  1x: The "PHPUnit\DeepCopy\TypeFilter\Spl\SplDoublyLinkedListFilter" class is considered final. It may change without further notice as of its next major version. You should not extend it from "PHPUnit\DeepCopy\TypeFilter\Spl\SplDoublyLinkedList".

Any help would be appreciate

**Comment by theofidry** [comment]
As said previously: there is not much to do. This deprecation is legit within the codebase and it serves as a warning if you were extending `SplDoublyLinkedListFilter`. DeepCopy won't be able to solve this deprecation before 2.0.
