### ISSUE TITLE
re-install Laravel website problems

### ISSUE THREAD

**Issue by amodisc** [myclabs/DeepCopy#150]
Hi I lost my server by accidentally deleting the disc.  Its On Centos 7 (with ElasticHosts- who say they don't have a backup).

I have managed to reinstall the files that were in the www folder where I had all my php stuff in Laravel format.  I also got ssl installed, mysql (and uploaded a copy of my lost database) so it all looks fine on the outset.  I have PHP 7.1 installed. The server is working in that I can access the root document from a browser but it won't route as it should with Laravel.

However it should be routing to my welcome page as set up with Laravel, but instead it is blank.  When I look at the error log it says:

 PHP Parse error:  syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\\\ (T_NS_SEPARATOR) in /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/deep_copy.php on line 5

When I look at other threads it says its a problem with the PHP version, but this is my PHP version:

PHP 7.1.33 (cli) (built: Feb 18 2020 07:15:58) ( NTS )
Copyright (c) 1997-2018 The PHP Group

(I have also tried 7.0 and 7.2 but still the same error).

Can anyone help me get it back? Please

A

**Comment by amodisc** [comment]
IT's Ok I found the problem.  I had an old copy of PHP 5.5 lingering around,  I removed it and the error went away.

**Comment by theofidry** [comment]
Glad to hear :)
