### ISSUE TITLE
doc\clone.png failed to open stream

### ISSUE THREAD

**Issue by camilord** [myclabs/DeepCopy#151]
I am getting an error on:
```
- Updating myclabs/deep-copy (1.7.0 => 1.9.5): Loading from cache

  [ErrorException]
  copy(E:\localhost\gitlab\alpha1v1\vendor/myclabs/deep-copy/doc\clone.png): failed to open stream: Permission denied
```
any luck solving this issue?

**Comment by theofidry** [comment]
Maybe a solution is to exclude the doc & tests from the artefact. I hardly see anything else actionable here unfortunately

**Comment by mnapoli** [comment]
Good point, I pushed a491d65139e2411c75704e871dd02bdddf5a4bdc just in case.

But yes, here it seems to be a permission issue that is unfortunately not related to this package AFAICT.
