### ISSUE TITLE
proc_open(): CreateProcess failed, error code - 5 

### ISSUE THREAD

**Issue by jianyan74** [myclabs/DeepCopy#162]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 5 installs, 3 updates, 0 removals
  - Updating myclabs/deep-copy (1.10.1 => 1.10.2):
                                                     
  [ErrorException]                                   
  proc_open(): CreateProcess failed, error code - 5

**Comment by mnapoli** [comment]
This seems like a Composer error of some kind, I don't think it's related to this project.
