### ISSUE TITLE
DeepCopy misses private properties of parent classes

### ISSUE THREAD

**Issue by mrthehud** [myclabs/DeepCopy#17]
I believe this is due to the way it iterates over properties using ReflectionObject::getProperties().

Is this expected, or undefined behaviour? I can't decide :\

**Comment by mnapoli** [comment]
Good question, it would probably be better to copy also those properties I think. Feel free to submit a pull request if you think it's worth fixing.

**Comment by mrthehud** [comment]
I'll do what I can, when I can, but can't guarantee it'll make it far enough up my todo list for a while ;)

**Comment by mnapoli** [comment]
Fixed by #23
