### ISSUE TITLE
Clone error 

### ISSUE THREAD

**Issue by emil-1996** [myclabs/DeepCopy#185]
![image](https://user-images.githubusercontent.com/55382634/224318954-94efe37b-72d4-481e-9050-e2521acbd4b1.png)

CODE:

![image](https://user-images.githubusercontent.com/55382634/224319002-015ed88b-39a0-4b18-affd-337d138e1751.png)

**Comment by mnapoli** [comment]
Somehow your class seems to have a reference to the container. Moving to a discussion as this is a support question, not an issue in the project.
