### ISSUE TITLE
The class \"ContainerKL2EgoF\\App_KernelDevDebugContainer\" is not cloneable.

### ISSUE THREAD

**Issue by JoDrm** [myclabs/DeepCopy#190]
```
        $copier = new DeepCopy();
        $copy = $copier->copy($oldTemplateRevision);
```
this throw this error : 
`The class \"ContainerKL2EgoF\\App_KernelDevDebugContainer\" is not cloneable.
`

What is the problem ?

**Comment by mnapoli** [comment]
It means the class is not cloneable, you need to add filters to exclude it from the copying: https://github.com/myclabs/DeepCopy#going-further
