### ISSUE TITLE
DroctrineEmptyCollectionFilter does not work with Symfony2

### ISSUE THREAD

**Issue by melchione** [myclabs/DeepCopy#21]
Hello,

I have a Symfony2 project with Doctrine2 and I try to use DroctrineEmptyCollectionFilter so as to reset a array collection property while the deepCopy but it does not seem to work. The property keeps his array with all the data from the copied object : 

 $styleProperty = $em
                    ->getRepository('MyAppMainBundle:StyleProperty')
                    ->findOneById(9);

$deepCopy = new DeepCopy();
$deepCopy->addFilter(new DoctrineCollectionFilter(), new PropertyTypeMatcher('Doctrine\Common\Collections\Collection'));

$deepCopy->addFilter(
new DoctrineEmptyCollectionFilter(), new PropertyMatcher('MyApp\MainBundle\Entity\StyleProperty','stylePropertyByStyleElement'));

$newStyleProperty = $deepCopy->copy($styleProperty);       

Do I do something wrong?

**Comment by mnapoli** [comment]
I don't know what you are trying to do with #19 and this issue but it's definitely not motivating me to help you.

Try debugging using xdebug and identify the source of your problem.

**Comment by melchione** [comment]
I fixed the problem with #19 because I did just can't keep a manytomany relation. But when I try to set an arrayCollection as null with your system and when I use xdebug the arrayCollection is still populated.

May I did not understood how to use your plugin.

PS: sorry for #19 I edited the post while I tried to find the solution.

**Comment by travelerClub** [comment]
I found a solution, when you add DoctrineCollectionFilter and DoctrineEmptyCollectionFilter to properly ignore the desired array collection, you have to add the DoctrineEmptyCollectionFilter before  DoctrineCollectionFilter:

`$deepCopy = new DeepCopy();

$deepCopy->addFilter(
new DoctrineEmptyCollectionFilter(), new PropertyMatcher('MyApp\MainBundle\Entity\StyleProperty','stylePropertyByStyleElement'));

$deepCopy->addFilter(new DoctrineCollectionFilter(), new PropertyTypeMatcher('Doctrine\Common\Collections\Collection'));
`

**Comment by deivid11** [comment]
I found a solution, when you add DoctrineCollectionFilter and DoctrineEmptyCollectionFilter to properly ignore the desired array collection, you have to add the DoctrineEmptyCollectionFilter before  DoctrineCollectionFilter:

$deepCopy = new DeepCopy();

$deepCopy->addFilter(
    new DoctrineEmptyCollectionFilter(), new PropertyMatcher('MyApp\MainBundle\Entity\StyleProperty','stylePropertyByStyleElement'));

$deepCopy->addFilter(new DoctrineCollectionFilter(), new PropertyTypeMatcher('Doctrine\Common\Collections\Collection'));
