### ISSUE TITLE
Maximum function nesting level of '200' reached, aborting

### ISSUE THREAD

**Issue by raoul2000** [myclabs/DeepCopy#26]
Hi,
I've updated to 1.4.0 and my tests failed with a *Maximum function nesting level of '200' reached, aborting* exception.

Rolled back to 1.3.1 everything went back to normal.

I don't know if I missed something (config or ... something) but I thought you might be notified.

thanks

**Comment by mnapoli** [comment]
Hi, in 1.4.0 more stuff is copied: private properties of parent classes.

So it could be that a private property in a parent class is pointing to a very big object graph? (Doctrine, …)

Could you try increasing the max nesting level a lot (something like 10000 just temporarily, to try) and see if it succeeds?

If it fails, that means there's an infinite loop in this package (so it's a bug to fix). If it succeeds, I would say that means you need to exclude the parent (private) properties else you are cloning (without realizing it) a lot of stuff.

**Comment by raoul2000** [comment]
Ok I will perform these test tomorrow and I'll let you know.

For the record the test I'm running is under CodeCeption + YII2

**Comment by raoul2000** [comment]
I made the test with 10000 for max nesting level and it works .. well at last it doesn't fire any exception. 

.. *but* now the problem is that my tests can't be executed in an acceptable amount of time : from 5 seconds with v 1.3.1 we reach more than 2 minutes with 1.4.0, and a huge amount of memory being allocated (to be honest I killed the process after 2 minutes :smirk: )

So I assume that, I should follow your advice and exclude parent private properties to reduce the overload right ? Can you please tell me how to do that ? I couldn't find doc about it...

Thanks for your help

**Comment by mnapoli** [comment]
Ok that's reassuring. You have several options for parent private properties (or for any property):

- clone them (default behavior)
- keep their value (not cloning, just reuse the existing value)
- set them to null

Since the first one isn't good for you, you can choose any other one. To keep the value you can use a [`KeepFilter`](https://github.com/myclabs/DeepCopy#keepfilter) or to set to null a [`SetNullFilter`](https://github.com/myclabs/DeepCopy#setnullfilter). However you have to identify the property that's causing your problem. To do that you can use debugging (XDebug) or maybe dump (var_dump) the object to see what it contains.

**Comment by raoul2000** [comment]
I will do that then..

Thanks again for your help

**Comment by githubjeka** [comment]
Can you help me ?
https://travis-ci.org/githubjeka/githubjeka/yii2-tutorial/builds/88070563#L422

**Comment by mnapoli** [comment]
@githubjeka sure thing, please read the thread. There's a parent (private) property in your object that is copied, and it's possible it contains a very big object graph (Doctrine, …).

**Comment by githubjeka** [comment]
My tests are passing on local-server :(

Ok I will understand...

**Comment by mnapoli** [comment]
@githubjeka OK in that case that's probably the xdebug configuration that sets the max_nesting_level to 200 (which is quite small). Have a look at changing that value on Travis. Or maybe dig in: it may be a signe something weird is happening.

**Comment by githubjeka** [comment]
Setting `phpenv config-rm xdebug.ini` in travis-ci resolves the issue.
