### ISSUE TITLE
KeepFilter and PropertyTypeMatcher

### ISSUE THREAD

**Issue by fsevestre** [myclabs/DeepCopy#27]
It is currently possible to use the `KeepFilter` with the `PropertyTypeMatcher` (no exception thrown) but it's not working:
```
$deepCopy = new DeepCopy();
...
$deepCopy->addFilter(new KeepFilter(), new PropertyTypeMatcher('AppBundle\Entity\Group'));
...
$versionCopy = $deepCopy->skipUncloneable()->copy($version);
```
I have this error:

```
Doctrine\ORM\ORMInvalidArgumentException: A new entity was found through the relationship 'AppBundle\Entity\Version#groups' that was not configured to cascade persist operations for entity: AppBundle\Entity\Group@000000003121925c000000001779ad23. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'AppBundle\Entity\Group#__toString()' to get a clue.
```

The `filters` property is iterate after cloning the object (https://github.com/myclabs/DeepCopy/blob/master/src/DeepCopy/DeepCopy.php#L137), but should be checked before the clone (https://github.com/myclabs/DeepCopy/blob/master/src/DeepCopy/DeepCopy.php#L119).

**Comment by mnapoli** [comment]
Is "group" in a collection? Filters and matchers are only applied to object properties. If groups are indeed in an array or a collection, then filters and matchers will not be applied to it.

The original decision as to *why* filters and matchers are applied to object properties (and not to objects directly) is that deciding on what to do (keep, replace, clone, etc.) depends a lot on the context. For example  `User::$id` isn't the same as `Group::$id`, just like you might not want the same behavior for `User::$group` and `Group::$parentGroup`. So you always want to apply filters for an object but **in the context of a property**.

Now that we have this limitation, your code can't work. One solution is to do something like this:

```php
$deepCopy->addFilter(new VersionGroupFilter(), new PropertyMatcher('AppBundle\Entity\Version', 'group'));
```

and `VersionGroupFilter` being something like:

```php
class PropertyMatcher implements Matcher
{
    public function matches($groupCollection, $property)
    {
        // Clone the group collection but keep its content e.g.
        return new ArrayCollection($groupCollection->toArray());
    }
}
```

**Comment by mnapoli** [comment]
Please have a look at the last version (1.5.0) which allows to apply filters to anything (i.e. not just object's properties). See #28

**Comment by fsevestre** [comment]
:+1: Sounds great, thanks. I'll try this on monday :)
