### ISSUE TITLE
Entity User is not clonable

### ISSUE THREAD

**Issue by andreaslarssen** [myclabs/DeepCopy#30]
Hi.

Great lib, seems to do just what I need.
Trying it for the first time, and having some trouble.

I have a survey entity fetched from db:

```
$surveyEntity = $em->getRepository('AppSurveyBundle:Survey')->findOneBy(array('id' => $surveyId, 'deleted' => null));
```

This is the entity I want to clone, so;

```
$deepCopy = new DeepCopy();
$deepCopy->addFilter(new SetNullFilter(), new PropertyNameMatcher('id'));
$newSurveyEntity = $deepCopy->copy($surveyEntity);
```

Trying to run this, I get an exception telling me that "'App\UserBundle\Entity\User' is not cloneable.".
This entity is not referenced anywhere in my entity as far as I can tell. Searched through the entire bundle for any signs of "user", but there are none, as expected. My user entity has nothing to do with the survey entity.

Any pointers for me debugging this? 
What makes an entity un-clonable?

**Comment by mnapoli** [comment]
Could it be that the `$surveyEntity` is a Doctrine proxy? That would explain why it has properties containing other objects maybe. There is #18 on that topic.

**Comment by andreaslarssen** [comment]
It could be that the copy will fail, caused by my entity being a proxy, but I still don't understand why it's trying to clone entities not referenced (as far as I know / can see) in my survey entity or any of it's collections. I'll read some more docs, and play around with it a little. Thanks for the quick response.

**Comment by mnapoli** [comment]
If it's a proxy then (IIRC) the proxy has references to big objects (like the entity manager). So DeepCopy tries to copy a very big object graph. I'll close this as duplicate to #18, please continue the discussion if you find anything else.

**Comment by andreaslarssen** [comment]
Wow, that's totally bonkers (the proxy having that many references). I'll continue in #18 then.
