### ISSUE TITLE
How to deal with uncloneable objects ?

### ISSUE THREAD

**Issue by Jan0707** [myclabs/DeepCopy#31]
Hey guys, I am facing a bit of dilemma here. The situation is as follows:

I am currently trying to clone a rather complex tree of documents that I retrieved via doctrine from MongoDB. In order to persist the newly clones documents again, I need to either strip them of their ids or replace new them with new ids (\MongoId to be precise).

My initial approach therefore was to either use replace filter or a setNullFilter like this:

```$deepCopy->addFilter(new SetNullFilter(), new PropertyNameMatcher('id'));```

But then I ran into the exception that DeepCopy still encountered some MongoId Objects that are uncloneable (Which is how I stumbled over the bug I fixed the other day). As it turns out, MongoId Objects are also used in properties that are not called 'id'. Still I thought the fix was rather easy:

```$deepCopy->addFilter(new SetNullFilter(), new PropertyTypeMatcher('MongoId'));```

After all, this approach should handle all Objects of the MongoId kind, right ? In fact, it does but not in the way I intended it to. It turns out, we use MongoId Objects to reference other objects. These references however should be kept during copying and not be nulled.

Still, I thought the fix was rather easy. I just write my own filter that either duplicates the id manually or keeps it, depending on the property name:

```<?php

use DeepCopy\Filter\Filter;

class MongoIdFilter implements Filter
{
    /**
     * {@inheritdoc}
     */
    public function apply($object, $property, $objectCopier)
    {
        $reflectionProperty = new \ReflectionProperty($object, $property);
        $reflectionProperty->setAccessible(true);

        if ($property === 'id') {
            $value = new \MongoId();
        } else {
            ldd($reflectionProperty->getValue($object));

            $value = new \MongoId((string) $reflectionProperty->getValue($object));
        }

        $reflectionProperty->setValue($object, $value);
    }
}
 ```

Yet, I still run into the exception:

 ```
[DeepCopy\Exception\CloneException]
Class "MongoId" is not clone able.
```

Via debugging I found out that my filter is being executed, but apparently not in every case. I seem to be missing something. Is there any other, preferred way, I should handle this situation ?

Best regards

Jan

**Comment by jkuchar** [comment]
Isn’t this same problem as #24 where there was problems with array members?

BTW isn’t it better to use type matcher instead of property matcher.

**Comment by Jan0707** [comment]
I don't think it's the same problem.

Am I not using a type matcher here ?
```$deepCopy->addFilter(new SetNullFilter(), new PropertyTypeMatcher('MongoId'));```

**Comment by jkuchar** [comment]
Interfaces `Filter` and `TypeFilter` are different. Filter is executed only on object properties; type filter checks also arrays contained in properties.

**Comment by Jan0707** [comment]
Indeed, but if I were to use a ```TypFilter```` like this:
```
interface TypeFilter
{
    /**
     * Apply the filter to the object.
     * @param mixed $element
     */
    public function apply($element);
}

```

The interface clearly states that the apply function is only called with the ```$element```. But as you can see in the example code above, I also need the property name to decide what to do.

**Comment by jkuchar** [comment]
Yep, that is true. In property filter you have to manually iterate over arrays. That’s it.

**Comment by mnapoli** [comment]
> Via debugging I found out that my filter is being executed, but apparently not in every case.

Are you able to see what those cases are? @jkuchar suggested they might be in objects that are in arrays, could be it…

Also there's an option to skip uncloneable objects: https://github.com/myclabs/DeepCopy/blob/master/src/DeepCopy/DeepCopy.php#L42 It might be what you are looking for?

**Comment by Jan0707** [comment]
> Also there's an option to skip uncloneable objects
I'll have a look into it, but I do not think that simply not copying the objects and then posting to the original object, will work well with doctrine's unit of work.

Array might also be an possibility, I'll check that.

**Comment by jkuchar** [comment]
Then please try to propose a solution and post PR. When something does not work, the best way of fixing it is to create test and describe exctly intended behaviour there.

**Comment by Jan0707** [comment]
I am more than glad to implement a solution, I just wanted to check back with you guys, what the best approach would be, since I would like this feature to be merged back into the repo. So I kind of need your blessing ;)

Anyway, I tried to come up with a test case that demonstrates what I am looking for:

https://gist.github.com/Jan0707/9aeb502cd72e8dbdb890

**Comment by jkuchar** [comment]
It looks like MongoId is not clone-able. So you need to do two things:
1) implement filter to clone all instances of MongoId manually (->addTypeFilter)
2) Filter those instances you do not want to clone (->addFilter)

**Comment by Jan0707** [comment]
Thanks a bunch ! I updated the gist: https://gist.github.com/Jan0707/9aeb502cd72e8dbdb890

Guess the problem was that I was not aware that you could combine TypeFilter and ordinary Filters, I assumed DeepCopy would only execute the first one it finds suitable.
