### ISSUE TITLE
"FOS\UserBundle\Model\User" is not cloneable

### ISSUE THREAD

**Issue by jakenoble** [myclabs/DeepCopy#33]
Doing the following still tries to copy the User object - how do I stop this cloning happening?

```
$deepCopy = new DeepCopy();
$deepCopy->addFilter(new SetNullFilter(), new PropertyNameMatcher('user_id'));
$deepCopy->addFilter(new SetNullFilter(), new PropertyNameMatcher('user'));
$clone = $deepCopy->copy($entity);
```

**Comment by jkuchar** [comment]
Please note that his is not a support forum. This is issue tracker. Please try to izolate this problem before posting it here.
