### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by tchiotludo** [myclabs/DeepCopy#37]
Hello, 

There is some fix on master : 
https://github.com/myclabs/DeepCopy/compare/1.5.0...master

especially this one : https://github.com/myclabs/DeepCopy/pull/29

Can you bump version please in order to avoid rely on dev-master please ? 

thanks

**Comment by mnapoli** [comment]
Hi  

I'm away from a computer right now but I'll do it asap  



Le 25 avril 2016 à 10:48:09, tchiotludo (notifications@github.com(mailto:notifications@github.com)) a écrit:

**Comment by mnapoli** [comment]
I've tagged [1.5.1](https://github.com/myclabs/DeepCopy/releases/tag/1.5.1).

**Comment by tchiotludo** [comment]
Thanks a lot
