### ISSUE TITLE
Doctrine 2 persisting new objects

### ISSUE THREAD

**Issue by pdobrigkeit** [myclabs/DeepCopy#39]
I know your project is used more braodly. But I am using Doctrine 2 and trying to copy entites, which are now generated, but cannot be written to the database because they are not persistet. I can and will not set cascading persists in our project, so I was wondering if I can use the filter mechanism to persist entities upon creation?

**Comment by mnapoli** [comment]
Hi, yes you could. You could also take your cloned object graph and try to iterate on all the objects it contains (using the getters of your objects assuming there are) to persist them.
