### ISSUE TITLE
Use a factory for DeepCopy

### ISSUE THREAD

**Issue by theofidry** [myclabs/DeepCopy#47]
Is there a reason not to have a factory to always return the same instance of `DeepCopy`? Creating a new instance each time comes with an overhead and prevent any use of the internal cashing as nothing is static. For [this profile](https://blackfire.io/profiles/compare/56d6a756-c32f-4755-b0ba-0b8f48f6ab88/graph), you can see that it can get quite bad. To be taken with a grain of salt as in the benchmark I was creating a new instance of DeepCopy which has a certain overhead for sure, but from the profiling you can see that most of the time lost comes from the cashing.

**Comment by mnapoli** [comment]
A factory is only responsible for creating an object, not caching it -> that would make the whole thing a singleton/static accessor (which is of course not a good idea).

Today dealing with the instance of the service is the responsibility of the user, just like with any other package AFAIK (e.g. Symfony's translator, Twig's instance, etc. etc.). When using a DI container it's not an issue at all (you configure DeepCopy once, it gets created once and injected everywhere needed).

**Comment by theofidry** [comment]
Giving an alternative to DI is good as well. To take the example of Symfony components, you do have `PropertyAccess` which a factory implementing the singleton pattern.

I'm actually more concerned about the cache system of `DeepCopy`: it uses `spl_object_hash` which can be given to two very different objects if the first one has been unset. If you create a new instance you reduce the chances to have this issue, but I have no idea how much you raise the likelihood of having this issue by having a single instance.

**Comment by mnapoli** [comment]
The hashmap is reset each time `copy()` is called (https://github.com/myclabs/DeepCopy/blob/master/src/DeepCopy/DeepCopy.php#L55). Yes it's not the cleanest solution ever ;) but well it works

**Comment by theofidry** [comment]
Oh I missed that. Hm ok so there is no real point for a factory then...
