### ISSUE TITLE
Document #46

### ISSUE THREAD

**Issue by theofidry** [myclabs/DeepCopy#52]
Besides documenting it, I would even recommend it. IMO the biggest selling point of DeepCopy is it's ease of use even on array structures. I don't really like the OOP usage of it and prefer to put it in a function instead like in alice: https://github.com/nelmio/alice/blob/master/src/functions.php#L12

However that's it: I use it because it's convenient. The other selling point of the library is handling cycling graph, but 9/10 a cycling graph is due to a mistake somewhere. Not that there isn't legitimate use cases, but they are very rare.

**Comment by mnapoli** [comment]
I'm all for it 👍 

I just discovered you are using this library in alice, that's really great!

**Comment by theofidry** [comment]
>I just discovered you are using this library in alice, that's really great!

I dare say I'm *over* using it 😄

**Comment by theofidry** [comment]
Closed by #89
