### ISSUE TITLE
Mongo BSON objects are not cloneable

### ISSUE THREAD

**Issue by hackel** [myclabs/DeepCopy#57]
Specifically, `Class "MongoDB\BSON\ObjectID" is not cloneable.`  This is a trivial object that simply contains a 24 character hex string.  Cloning it is trivial:
```php
$orig = new ObjectID;
$clone = new ObjectID((string) $orig);
```
I suspect there may be issues with the other BSON types as well, but there's no reason these shouldn't be easily cloneable.  It might make more sense to wait for Mongo to get their act together and fix their extension, though.

**Comment by theofidry** [comment]
@hackel I don't think DeepCopy should do anything here.

To me (@mnapoli may have a different vision and correct me), there is two use cases for DeepCopy:

- Use to ensure real deep cloning, that might be necessary in libraries like PHPUnit or weird cases where you might have circular references
- A more common userland deep cloning which should not be much more than calling a regular `clone`, check recursively for arrays or simple do nothing on scalar values

From the error it looks like BSON objects, or at least `ObjectID` prevents any `clone` call. There might be a reason to it, but I don't think DeepCopy should implement custom ways of cloning. If you want to do that, I would rather recommend to extend/decorate it instead.

**Comment by mnapoli** [comment]
:+1: to me we shouldn't do anything specific here, you can use filters and matchers to clone `ObjectID` properly.

**Comment by hackel** [comment]
Yes, that makes more sense, thanks.
