### ISSUE TITLE
Duplicate entity on persist.

### ISSUE THREAD

**Issue by Vansamang** [myclabs/DeepCopy#60]
When I save an deepcloned entity, the entity is saved double.

A code snippet

```
$deepCopy = new DeepCopy();

$deepCopy->addFilter(new DoctrineCollectionFilter(), new PropertyTypeMatcher('Doctrine\Common\Collections\Collection'));

$copy = $deepCopy->copy($item);
//Frefresh the old item
$em->refresh($item);
//Detach the clone
$em->detach($copy);
//Persist the clone
$em->persist($copy);

$em->flush();

```

**Comment by theofidry** [comment]
Isn't it the expected behaviour? The copy is completely detached: persisting it will will save the entity. What you did is:

- have `$copy` and `$item` with the same data
- refresh `$item`, so `$item` is saved
- persist `$copy`

**Comment by Vansamang** [comment]
refresh should load the item not save the item, or am I wrong?

**Comment by theofidry** [comment]
Yes but that means it's already saved

**Comment by theofidry** [comment]
Closing as explained [here](https://github.com/myclabs/DeepCopy/issues/60#issuecomment-338021321), that's the expected behaviour unless I misunderstood something.
