### ISSUE TITLE
PropertyTypeMatcher shouldn't be deprecated whilst type-filter doesn't support the same set of filters

### ISSUE THREAD

**Issue by Bilge** [myclabs/DeepCopy#61]
Problem: `KeepFilter` is only implemented as a regular filter, so to apply it by type one must use the deprecated `PropertyTypeMatcher`. Ergo `PropertyTypeMatcher` should not be deprecated until all the regular filters are implemented as type filters.

That is, it's a bad idea to deprecate something without providing an alternative.

**Comment by mnapoli** [comment]
Thanks, please have a look at #64

**Comment by mnapoli** [comment]
Seems like I forgot to merge…
