### ISSUE TITLE
Matches are expected to access private properties in a derived class

### ISSUE THREAD

**Issue by Bilge** [myclabs/DeepCopy#62]
I'd like to start off by saying I am very surprised a basic inheritance issue such as this still exists in software that has been in development for four years.

As demonstrated in the following example, the filter's matcher (i.e. `PropertyTypeMatcher`) is expected to access a private property of the parent class in a derived class. Needless to say, it fails, because the property does not exist in the derived class.

```php
class A {
    private $foo;

    public function __construct($foo) {
        $this->foo = $foo;
    }
}

class B extends A {}

$copier = new DeepCopy;
$copier->addFilter(new KeepFilter, new PropertyTypeMatcher(stdClass::class));
$copier->copy(new B((object)[]);
```

>Property B::$foo does not exist
> src\DeepCopy\Matcher\PropertyTypeMatcher.php:33

**Comment by mnapoli** [comment]
Thanks for the report, this looks indeed like a bug. I don't have time to fix this myself but if anyone wants to have a go at it pull requests are welcome (have a look at #63 for a failing test case).
