### ISSUE TITLE
Mark classes as final

### ISSUE THREAD

**Issue by theofidry** [myclabs/DeepCopy#66]
A fair amount of those classes, to not say all, should be final. While it's not doable in 1.x, maybe we could mark them as `@final` already.

**Comment by IMM0rtalis** [comment]
But why? Can you explain a bit more?

**Comment by theofidry** [comment]
This allows us to make changes more easily as we don't have to worry about how the classes are extended. You can see in #78 that there is two cases:

- the classes are fairly simple and implement an interface: inheritance has no value there
- the class has no interface but no extension point offered by inheritance, so no point to allow inheritance there either
