### ISSUE TITLE
Change Matcher API

### ISSUE THREAD

**Issue by theofidry** [myclabs/DeepCopy#67]
Right now an matcher gets a string as a second argument, cf. [this line](https://github.com/myclabs/DeepCopy/blob/master/src/DeepCopy/DeepCopy.php#L188). IMO this is quite inefficient for two reasons:

- First `ReflectionProperty` is much more powerful and easy to manipulate than just a name. For example in [PropertyTypeMatcher](https://github.com/myclabs/DeepCopy/blob/master/src/DeepCopy/Matcher/PropertyTypeMatcher.php) we end up doing reflection again... when it could be just passed down.
- It is actually wrong. If you take the example above (PropertyTypeMatcher), the property could come from a parent class and as a result the reflection will throw an exception. While if you pass the `ReflectionProperty`, you actually get the right one.

**Comment by mnapoli** [comment]
If it works the way you want to do it (and it's better in terms of performances) then feel free to send a pull request.

**Comment by theofidry** [comment]
@mnapoli that would be a BC break so it would be for 2.x only. Maybe we should prepare it by creating a 1.x branch?

**Comment by IMM0rtalis** [comment]
+1 
and for DoctrineProxy-objects it is not even working, since the parent-class-properties could be private, then ReflectionProperty is not fetching them without another helping-function.

**Comment by IMM0rtalis** [comment]
there are now branches for 2.x and 1.x  . I'll join you on this issue here, but first i am at holiday for a week, so after then ;)

**Comment by Slamdunk** [comment]
I think this can be considered closed by https://github.com/myclabs/DeepCopy/pull/107

**Comment by theofidry** [comment]
Indeed, thanks :)
