### ISSUE TITLE
Provide an utility function

### ISSUE THREAD

**Issue by theofidry** [myclabs/DeepCopy#69]
More an idea than a feature request. In some of my applications I often end up with something like that:

```php
if (false === function_exists('deep_clone')) {
    /**
     * Deep clone the given value.
     *
     * @param mixed $value
     *
     * @return mixed
     */
    function deep_clone($value)
    {
        return (new \DeepCopy\DeepCopy())->copy($value);
    }
}
```

e.g. in the wild: [alice](https://github.com/nelmio/alice/blob/master/src/functions.php) (it's not the only one).

Which actually could be enhanced by being put in a namespace like done in [nikic/iter](https://github.com/nikic/iter/blob/master/src/iter.php):

```php
namespace MyNamespace;

    /**
     * Deep clone the given value.
     *
     * @param mixed $value
     *
     * @return mixed
     */
    function deep_clone($value)
    {
        return (new \DeepCopy\DeepCopy())->copy($value);
    }
}
```

I think it could be a nice to have as makes it easier to use (provided you don't have custom config to do).

**Comment by mnapoli** [comment]
:+1:
