### ISSUE TITLE
Create branch 2.0

### ISSUE THREAD

**Issue by IMM0rtalis** [myclabs/DeepCopy#73]
In several issues i read a lot of nice ideas how to improve this nice project. But like already suggested from others I would like to have a branch 2.0 or sth like this. Can you create this pls?

**Comment by theofidry** [comment]
I'll try to do that in the evening. Feel free to ping me if I forgot, it's not that it takes long but there's some links that needs to be fixed after

**Comment by IMM0rtalis** [comment]
but do the links need to be adjusted before we release sth as version 2.0 ?

**Comment by theofidry** [comment]
I've just pushed a `2.x` branch which you can now target
