### ISSUE TITLE
New Release?

### ISSUE THREAD

**Issue by araines** [myclabs/DeepCopy#79]
Hi
Any chance of a new release please?  A couple of fixes have made their way in now which I'm reliant on and I'd prefer not to be running from dev-master if at all possible!

Thanks!

**Comment by theofidry** [comment]
Hi @araines,

Yeah sorry I'm aware I'm a bit slow on this project right now. I'm quite busy between work and movings at the moment. But I'm still using this library and need some changes so don't worry I'll come back to it soonish 🙇

**Comment by theofidry** [comment]
@mnapoli I can do a new release now. Do you mind removing the `master` branch (we already have 2.x) and moving `1.x` as the default branch? I can't do that with my current access permissions

**Comment by mnapoli** [comment]
Permissions should be all good now feel free to do whatever you need! Really like those doc improvements!

**Comment by theofidry** [comment]
Thanks :)

@araines [1.7.0](https://github.com/myclabs/DeepCopy/releases/tag/1.7.0) has been released ✨
