### ISSUE TITLE
can't clone with hhvm

### ISSUE THREAD

**Issue by karser** [myclabs/DeepCopy#8]
the same code is working with php-fpm and fails on hhvm.
```
            $deepCopy = new DeepCopy();
            $deepCopy->addFilter(new DoctrineCollectionFilter(), new PropertyTypeMatcher('Doctrine\Common\Collections\Collection'));
            $deepCopy->copy($object);
```
Uncaught PHP Exception BadMethodCallException: "Trying to clone an uncloneable object of class ReflectionClass" at line {"exception":"[object] (BadMethodCallException(code: 0): Trying to clone an uncloneable object of class ReflectionClass at :)

hhvm --version
HipHop VM 3.5.0-dev (rel)
Compiler: heads/master-0-gcb697d9b910189e25fbddce39e7672dfd27d4f04
Repo schema: 8b97230efbcbe284b1e86ce2768b04e5145b36f2
Extension API: 20140829

**Comment by mnapoli** [comment]
Hi, thanks for reporting this. Do you think it's a bug in HHVM?

By the way there's an option to skip uncloneable classes: https://github.com/myclabs/DeepCopy/commit/6247d82c1b441fdbcf12f67f4f134ce68d7ee87c

Too bad it's not yet documented, but give it a try, maybe it will help you workaround the problem.
