### ISSUE TITLE
Change object class when copying

### ISSUE THREAD

**Issue by Koc** [myclabs/DeepCopy#9]
We should create copy of entity with cnahging it class (doctrine single table inheritance). Currently library doesn't support this.

**Comment by mnapoli** [comment]
I'm sorry I don't understand what you are trying to do. Have you tried using filters?

**Comment by Koc** [comment]
There are classes `AbstractDemand`, `PublicDemand`, `PrivateDemand`. When user creates `PrivateDemand` sometimes we should create copy of this object, but it should be instance of `PublicDemand`.

It is impossible to do it with filters. Imho we can change signature of `copy` method like

```php
public function copy($object, $targetObject = null)
```

And `copyObject`
```php
$newObject = $targetObject  ?: clone $object;
```

**Comment by mnapoli** [comment]
There is now a `ReplaceFilter` to replace the value of a property. In any case I think it's better to replace the object by another rather than try to change its class, it would lead to too many problems I'm afraid.
