### ISSUE TITLE
PHPUnit 6

### ISSUE THREAD

**Issue by carusogabriel** [myclabs/DeepCopy#93]
For `version 2.0` of this package, could we support `PHP 7` and use `PHPUnit 6`?

**Comment by theofidry** [comment]
Yep 👍 , I also think we can go straight to PHP 7.1

**Comment by carusogabriel** [comment]
@theofidry Can you please rebase `branch 2.x`? Then I can rewrite `Travis CI`, `Composer` and `PHPUnit` :tada:

**Comment by theofidry** [comment]
I'll try to this weekend, but to be honest there is a few more things that needs to happen in 1.x before we can make 2.x.

Most of the issues currently open should be doable in 1.x with a deprecation warning so that we can simply remove the deprecated stuff in 2.x

**Comment by theofidry** [comment]
I've taken a look and I'm afraid it's not simple work, I think I made sure what landed in 2.x was backported in 1.x but the way it will most likely go is take 1.x, cherry-pick what could not be backported on a new branch and push that new branch on 2.x. Maybe a proper merge would do but the quick attempt I did did not look simple
