### ISSUE TITLE
Bug in \DeepCopy\DeepCopy::copyObject method

### ISSUE THREAD

**Issue by lemaxya** [myclabs/DeepCopy#94]
Hi.
next lines in code are buggy, that our project failing today:
```
$objectHash = spl_object_hash($object);
..........
..........
$newObject = clone $object;
//One of two situations (I do not know correct solution)
//1)
$this->hashMap[spl_object_hash($newObject)] = $newObject; //<--- BUG: need use spl_object_hash($newObject) instead previous $objectHash

//2)
$this->hashMap[$objectHash] = $object;//<---- store old object
```

What is happening: The current $object will free (as cloned from previous recursions). The php reusing this $objectHash for new cloned $object. But in this case, the copy process returning old not correct $object from $this->hashMap. 

PLEASE fix it and inform me (I don't want to inject my codes inside ).

**Comment by theofidry** [comment]
AFAICS the code is correct, this hashmap is to avoid to have to clone again and again the same instance so the map is `object spl hash => cloned object`.

It may not be what you want but this is what it should do by default. I unfortunately can't help more than that without knowing what are your tests are about or a reproducer

**Comment by lemaxya** [comment]
The spl_object_hash($object) != spl_object_hash( clone $object)
But you storing $newObject in  $this->hashMap under not their objectHash.

And this is doing problems in deep copy.

**Comment by theofidry** [comment]
@lemaxya but this is correct. If you have:

```
stdClass#000 {
  - foo: stdClass#001
  - bar: stdClass#000
}
```

What you want as a result is:

```
stdClass#010 {
  - foo: stdClass#011
  - bar: stdClass#010
}
```

With your code that would result in a segfault because of an infinite recursion.

**Comment by lemaxya** [comment]
This version what I have:
   ```
 private function copyObject($object)
    {
        $objectHash = spl_object_hash($object);

        if (isset($this->hashMap[$objectHash])) {
            return $this->hashMap[$objectHash];
        }

        $reflectedObject = new \ReflectionObject($object);

        if (false === $isCloneable = $reflectedObject->isCloneable() and $this->skipUncloneable) {
            $this->hashMap[$objectHash] = $object;  //====== LIKE here ==========
            return $object;
        }

        if (false === $isCloneable) {
            throw new CloneException(sprintf(
                'Class "%s" is not cloneable.',
                $object->getName()
            ));
        }

        $newObject = clone $object;
        $this->hashMap[$objectHash] = $newObject; // ===== NEED $object (instead $newObject) like in code before ====

        foreach ($reflectedObject->getProperties() as $property) {
            $this->copyObjectProperty($newObject, $property);
        }

        return $newObject;
    }
```

**Comment by lemaxya** [comment]
@theofidry 
1) Do you have simple example for
> segfault because of an infinite recursion

understanding my version.

2) In our project next situation (see attached file, unprintable chars exists in file). Here is object A and deep copy result B. Stored by serialize() 


[AB.txt](https://github.com/myclabs/DeepCopy/files/1527881/AB.txt)

**Comment by theofidry** [comment]
I don't think I can follow this serialized code especially since I can't unserialize it. Would it be possible to get a reproducer?

**Comment by lemaxya** [comment]
Hi @theofidry 
Here is problem reproduce:
1) [index.txt](https://github.com/myclabs/DeepCopy/files/1530379/index.txt) (rename to index.php) - Deep clone object $a to $b and saving their print_r() to file  [A.txt](https://github.com/myclabs/DeepCopy/files/1530373/A.txt) and [B.txt](https://github.com/myclabs/DeepCopy/files/1530374/B.txt).
 But $a and $b having different content. That I see in diff application (see attached [screenshot](https://user-images.githubusercontent.com/6077179/33598835-d73539c2-d9ac-11e7-9417-9770a11dd5d8.png)) 

2) [composer.txt](https://github.com/myclabs/DeepCopy/files/1530396/composer.txt) (rename to composer.json) - only installing DeepCopy and ZendConfig (need for object $a)

Best Regards.

**Comment by lemaxya** [comment]
Hi @theofidry 
Any news helpful.
Thank you.

**Comment by theofidry** [comment]
Hi,

Sorry I don't have much time at the moment. I may be able to give it another look tonight but can't promise anything an this not change before the end of January as I have a busy new year

**Comment by lemaxya** [comment]
Hi Théo FIDRY.
Did you detect the issue?

**Comment by theofidry** [comment]
Nope, still quite busy for this month. If you really want to speed things up though what would be great is to have a PR with a failing test case. It's nice that you gave a reproducible case but the hard part for which I can't find any time yet is to manage to translate that into this failing test case to narrow down the issue and be able to fix it

**Comment by lemaxya** [comment]
I did check. In version 1.7.0 it is OK
Our project using 1.2.1 ( magic method __clone ).
Thank you.

**Comment by theofidry** [comment]
Eh, I guess it's time I require to ask the version installed with a template. Glad you sorted that out though :)
