### ISSUE TITLE
DoctrineEmptyCollectionFilter and DoctrineProxyMatcher are not used and have errors

### ISSUE THREAD

**Issue by elijah-z142** [myclabs/DeepCopy#99]
DoctrineEmptyCollectionFilter does not appear to be used in this repo, but it is there and also references "Doctrine\Common\Collections\ArrayCollection" which is not included.

Similarly, the class "Proxy" (Doctrine\Common\Persistence\Proxy) also does not exist is referenced by DoctrineProxyMatcher.

This does not affect the project's runtime, but I found this result through a kind of static analysis tool.

**Comment by theofidry** [comment]
Thanks for the report @elijah-z142 sorry for the late answer.

They are not used directly because `doctrine/collection` is a _soft_ dependency: there is a bridge for it in this library but by no means this dependency is required :)
